# Generated by Django 2.0.10 on 2019-02-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publicacion',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
